controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Existing controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - slider_11
 
